hostname = boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net

^https?:\/\/(.+\.)?boxjs\.(com|net) url script-analyze-echo-response https://raw.githubusercontent.com/Pythonming2020/qx-rules-mirror/main/mirror/chavyleung_scripts/chavy.boxjs.js
