#!name=FT中文网
#!desc=FT中文网pro (mirrored + patched expiry 2099)
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ft.png

^https?:\/\/user\.ftmailbox\.cn\/ios-receipt-validation\.php.* url script-response-body https://raw.githubusercontent.com/Pythonming2020/qx-rules-mirror/main/mirror/_custom/ftchinese.js

hostname=user.ftmailbox.cn
